/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.contenedor;

import modelo.Usuario;

/**
 *
 * @author xaca
 */
public class ContenedorReserva extends javax.swing.JPanel {

    private boolean estado;
    private Usuario usuario;
    
    /**
     * Creates new form ContenedorReserva
     */
    public ContenedorReserva() {
        initComponents();
    }

    public ContenedorReserva(Usuario usuario,boolean estado){
        
        initComponents();
        this.estado = estado;
        
        if(estado){
            
            jLabel1.setText("Disponible");
            jButton2.setVisible(false);
            jButton4.setVisible(false);
        }
        else
        {
            jLabel1.setText(usuario.getNombre());
            jButton1.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre");
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 14));
        add(jLabel1);
        add(filler1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Button-Add-icon.png"))); // NOI18N
        jPanel3.add(jButton4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon.png"))); // NOI18N
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Trash-can-icon.png"))); // NOI18N
        jPanel3.add(jButton2);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
